
db:
  image: postgres:9.5

postgrest:
  build: ./postgrest
  links: 
    - "db:pg"
  ports: 
    - "3000:3000"
  environment:
    - POSTGREST_AUTHENTICATOR=postgres
    - POSTGREST_DB=nyiso
    - POSTGREST_SCHEMA=api_v001
    - POSTGREST_ANONYMOUS=nyiso_admin


